### ISSUE TITLE
一些小建議

### ISSUE THREAD

**Issue by life1347** [cmcreborn/testK8s#1]
建議在 container port 內加上 protocol，以求更清楚描述 port 作用
```
ports:
- containerPort: 5566
   protocol: TCP
```

metadata 內加上 namespace， 未來改成 multi-tenancy 時就不必修改 YAML
```
metadata:
  name: demo-secret-from-yaml
  namespace: default
```

一般來說 secret, configmap 是用來唯獨不會更改，因此 readOnly = true 較佳
```
    volumeMounts:
    - name: secret-volume
      mountPath: /usr/share/nginx/html/username
      readOnly: true
```

第一個嘗試用 Dockerfile 修改 nginx 內容的學員!
感覺可以挑戰一下加分題，因為會改 nginx 內容就已經離正解不遠了 XD
